### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by andrewmcodes** [kirillian/shiplane#19]
I know we have talked about this before but can’t remember your stance on the subject. 

Would you be willing to adopt a code of conduct? I would be happy to open the PR. 

I personally am a fan of the [contributor covenant](https://www.contributor-covenant.org/)

It may seem pedantic but I do believe it is helpful in fostering a community to adopt a code of conduct, so the rules are clearly laid out and you can point to them in the case you come across behavior you deem unacceptable and want to point towards the reason you are removing a toxic person from the community. Here is my favorite reason from the contributor covenant faq: 

>It’s about establishing a minimal level of civil and professional collaboration. Civil, non-discriminatory, and professional behavior should be a baseline and shared value held by people of all ideologies, regardless of political affiliation

Let me know if you’d be willing to adopt this code of conduct or another. This version is very widely used which is why I usually reach for it first but I’m sure there are other good ones.

**Comment by kirillian** [comment]
Happily. I spent a bunch of time looking at this and I'd be happy to do so. My only concern was thinking through whether this made me liable to deal with certain situations in a specific way and I eventually decided that I would be willing to take on the duties that it would require of me. If you don't submit something before I finish adding these example files, I'll pull it myself and add it.

**Comment by andrewmcodes** [comment]
PR is up  👍

**Comment by kirillian** [comment]
Closing In light of #20
